#YAML es un lenguaje de serialización de datos diseñado para ser leído y escrito por humanos.
#Basa su funcionalidad en JSON, con la adición de líneas nuevas e indentación inspirada en Python.
version: '3'

services:

  # database container
  database1:
    image: postgres:10
    volumes:
      - ./database1_volume:/var/lib/postgresql/data
    env_file:
      - ./config/db/database1_env
    networks:
      - database1_network

  # web container, with django + gunicorn
  djangoapp:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/services/djangoapp/src
      - ./static:/opt/services/djangoapp/static
      - ./media:/opt/services/djangoapp/media
    networks:
      - database1_network      
      - nginx_network
    depends_on:
      - database1      

  # reverse proxy container (nginx)
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/opt/services/djangoapp/static
      - ./media:/opt/services/djangoapp/media
    networks:
      - nginx_network
    depends_on:
      - djangoapp

networks:
  database1_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  database1_volume:
  static:
  media:
